version: '3'
services:
  app: 
    container_name: learn-grpc-go-app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 50051:50051
    depends_on:
      - db
    networks:
      - learn-grpc-go
  db:
    image: postgres:15-alpine
    container_name: learn-grpc-go-db
    networks:
      - learn-grpc-go
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learn_grpc_go
networks:
  learn-grpc-go: {}